import { useEffect, useState } from 'react'
import { ApiError } from '../../shared/api/client'
import { createAssignment, decideAssignment, getAssignments, getDispatches, getRescueTeams, transitionDispatch, validateAssignment } from './api'
import type { AssignmentDto, DispatchDto, SafetyValidationWorkflowResultDto, SkillType, RescueTeamDto } from './types'
import './RescueCoordinationSection.css'

const skills: SkillType[] = ['WaterRescue', 'FirstAid', 'Paramedic', 'StructuralCollapse', 'FireResponse', 'Logistics', 'Driving']
const message = (error: unknown) => error instanceof ApiError ? ({ 401: 'Your session has expired or authentication is required.', 403: 'You do not have permission to perform this action.', 404: 'The selected record is no longer available.' }[error.status] ?? (error.status === 409 ? error.message : 'Unable to complete the request. Please try again.')) : 'Unable to complete the request. Please try again.'

export default function RescueCoordinationSection({ canCoordinate = false }: { canCoordinate?: boolean }) {
  const [teams, setTeams] = useState<RescueTeamDto[]>([]); const [assignments, setAssignments] = useState<AssignmentDto[]>([]); const [dispatches, setDispatches] = useState<DispatchDto[]>([])
  const [selected, setSelected] = useState<AssignmentDto | null>(null); const [validation, setValidation] = useState<SafetyValidationWorkflowResultDto | null>(null)
  const [teamId, setTeamId] = useState(''); const [vehicleId, setVehicleId] = useState(''); const [incidentId, setIncidentId] = useState(''); const [skill, setSkill] = useState<SkillType>('FirstAid'); const [capacity, setCapacity] = useState(1); const [notes, setNotes] = useState(''); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null)
  const refresh = async () => { setBusy(true); try { const [t,a,d] = await Promise.all([getRescueTeams(), getAssignments(), getDispatches()]); setTeams(t); setAssignments(a); setDispatches(d); setSelected(s => a.find(x => x.id === s?.id) ?? s) } catch (e) { setError(message(e)) } finally { setBusy(false) } }
  useEffect(() => { void refresh() }, [])
  const team = teams.find(t => t.id === teamId); const vehicles = team?.vehicles ?? []
  const canApprove = !!selected && !!validation?.workflowId && validation.assignmentId === selected.id && validation.planVersion === selected.planVersion && validation.decision === 'APPROVE' && !validation.isStale
  const create = async (e: React.FormEvent) => { e.preventDefault(); if (!canCoordinate) return; if (!incidentId || !teamId || !vehicleId || capacity < 1) return setError('Provide one Incident ID, a team, vehicle, and capacity.'); setBusy(true); try { const a = await createAssignment({ incidentId, helpRequestId: null, rescueTeamId: teamId, vehicleId, requiredSkill: skill, requiredCapacity: capacity, notes }); setSelected(a); setValidation(null); await refresh() } catch (x) { setError(message(x)) } finally { setBusy(false) } }
  const runValidation = async () => { if (!selected || !canCoordinate) return; setBusy(true); try { setValidation(await validateAssignment(selected.id)) } catch (x) { setError(message(x)) } finally { setBusy(false) } }
  const decide = async (decision: 'APPROVE' | 'REVISE' | 'REJECT') => { if (!selected || !validation?.workflowId || !canCoordinate) return; if (decision === 'APPROVE' && !confirm('The backend will perform a fresh live safety revalidation before dispatch. Continue?')) return; setBusy(true); try { await decideAssignment(selected.id, { workflowId: validation.workflowId, planVersion: selected.planVersion, decision, notes: null }); if (decision !== 'APPROVE') setValidation(null); await refresh() } catch (x) { setError(message(x)) } finally { setBusy(false) } }
  const next = (s: DispatchDto['status']) => s === 'Dispatched' ? 'EnRoute' : s === 'EnRoute' ? 'OnScene' : s === 'OnScene' ? 'Resolved' : null
  return <section className="rescue-coordination"><header className="panel__head"><div><h2 className="panel__title">Rescue coordination</h2><p className="panel__meta">Real assignments, AI safety review and human-controlled dispatch.</p></div><button className="btn-ghost" onClick={() => void refresh()} disabled={busy}>Refresh</button></header>{error && <div className="alert" role="alert">{error}</div>}
    <div className="rescue-summary"><span>Available teams: {teams.filter(t=>t.status==='Available').length}</span><span>On mission: {teams.filter(t=>t.status==='OnMission').length}</span><span>Active dispatches: {dispatches.filter(d=>!['Resolved','Cancelled'].includes(d.status)).length}</span></div>
    {!canCoordinate && <div className="alert">Read-only: rescue coordination actions require the Emergency Coordinator role.</div>}<div className="rescue-grid"><section className="panel"><h3>Rescue teams</h3>{teams.map(t=><div key={t.id}><strong>{t.name}</strong> — {t.status}<ul>{t.members.map(m=><li key={m.id}>{m.fullName}: {m.skill} ({m.isAvailable?'available':'unavailable'})</li>)}</ul><small>{t.vehicles.map(v=>`${v.plateNumber} · ${v.status} · capacity ${v.capacity}`).join(' | ')}</small></div>)}</section>
    <section className="panel"><h3>Create assignment</h3><form onSubmit={create}><label>Incident ID<input value={incidentId} onChange={e=>setIncidentId(e.target.value)} required disabled={!canCoordinate}/></label><label>Team<select value={teamId} onChange={e=>{setTeamId(e.target.value);setVehicleId('')}} required disabled={!canCoordinate}><option value="">Select team</option>{teams.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Vehicle<select value={vehicleId} onChange={e=>setVehicleId(e.target.value)} required disabled={!canCoordinate}><option value="">Select vehicle</option>{vehicles.map(v=><option value={v.id} key={v.id}>{v.plateNumber} — {v.status}, {v.capacity}</option>)}</select></label><label>Skill<select value={skill} onChange={e=>setSkill(e.target.value as SkillType)} disabled={!canCoordinate}>{skills.map(s=><option key={s}>{s}</option>)}</select></label><label>Required capacity<input type="number" min="1" value={capacity} onChange={e=>setCapacity(Number(e.target.value))} disabled={!canCoordinate}/></label><label>Notes<input value={notes} onChange={e=>setNotes(e.target.value)} disabled={!canCoordinate}/></label><button className="btn" disabled={busy||!canCoordinate}>Create proposal</button></form></section></div>
    <section className="panel"><h3>Assignments & AI safety review</h3>{assignments.map(a=><button key={a.id} className="btn-ghost" onClick={()=>{setSelected(a);setValidation(null)}}>{a.id.slice(0,8)} · {a.status} · v{a.planVersion}</button>)}{selected && <div><p>Assignment {selected.id} — {selected.status}, Plan Version {selected.planVersion}; Team {selected.rescueTeamName}; Vehicle {selected.vehiclePlateNumber}; {selected.requiredSkill}; capacity {selected.requiredCapacity}</p><button className="btn" disabled={busy} onClick={()=>void runValidation()}>Run AI Safety Validation</button>{validation && <div className="alert"><h4>AI Safety Validation: {validation.decision}</h4><p>{validation.summary}</p>{validation.checks.map(c=><p key={c.name}><strong>{c.passed?'PASS':'FAIL'}</strong> {c.name}: {c.reason}</p>)}<p><strong>AI recommendation only — human approval required.</strong></p><button className="btn" disabled={!canApprove||busy} onClick={()=>void decide('APPROVE')}>Approve & Dispatch</button><button className="btn-ghost" disabled={busy} onClick={()=>void decide('REVISE')}>Revise Plan</button><button className="btn-ghost" disabled={busy} onClick={()=>void decide('REJECT')}>Reject Plan</button></div>}</div>}</section>
    <section className="panel"><h3>Active dispatches</h3>{dispatches.map(d=>{const action=next(d.status); return <div key={d.id}><strong>{d.id.slice(0,8)}</strong> · {d.status} · Assignment {d.assignmentId.slice(0,8)} {action&&<button className="btn-ghost" onClick={async()=>{try{await transitionDispatch(d.id,action);await refresh()}catch(e){setError(message(e))}}}>Mark {action}</button>}</div>})}</section></section>
}
