import { useId, useState } from 'react'
import type { FormEvent } from 'react'
import { addTeamMember, addVehicle, createRescueTeam, deleteRescueTeam, removeTeamMember, removeVehicle, updateRescueTeam, updateTeamMember, updateVehicle } from './api'
import type { CreateTeamMemberRequest, CreateVehicleRequest, RescueTeamDto, SkillType, VehicleType } from './types'

const skills: SkillType[] = ['WaterRescue', 'FirstAid', 'Paramedic', 'StructuralCollapse', 'FireResponse', 'Logistics', 'Driving']
const vehicleTypes: VehicleType[] = ['Ambulance', 'Boat', 'FireTruck', 'FourByFour', 'Truck']

type FeedbackType = 'success' | 'error' | 'destructive'

function MemberPhoneField({ defaultValue = '' }: { defaultValue?: string }) {
  const errorId = useId()
  const [invalid, setInvalid] = useState(false)

  return <div className="rescue-member-phone">
    <input name="phone" type="tel" inputMode="numeric" aria-label="Phone" placeholder="Phone" defaultValue={defaultValue} required pattern="[0-9]{10}"
      aria-invalid={invalid} aria-describedby={invalid ? errorId : undefined}
      onInvalid={(event) => { event.preventDefault(); setInvalid(true) }}
      onChange={(event) => { if (/^[0-9]{10}$/.test(event.currentTarget.value)) setInvalid(false) }} />
    {invalid && <span id={errorId} className="rescue-member-phone__error" role="alert">Invalid phone number, Please check</span>}
  </div>
}

export default function ResourceManagementPanel({ teams, refresh }: { teams: RescueTeamDto[]; refresh: () => Promise<void> }) {
  const [newTeam, setNewTeam] = useState('')
  const [notice, setNotice] = useState<{ message: string; type: FeedbackType } | null>(null)
  const [busy, setBusy] = useState(false)
  const run = async (work: () => Promise<unknown>, success: string, type: Exclude<FeedbackType, 'error'> = 'success') => { setBusy(true); setNotice(null); try { await work(); await refresh(); setNotice({ message: success, type }); return true } catch (error) { setNotice({ message: error instanceof Error ? error.message : 'Unable to change this resource.', type: 'error' }); return false } finally { setBusy(false) } }
  const createTeam = (event: FormEvent) => { event.preventDefault(); if (!newTeam.trim()) return; void run(() => createRescueTeam({ name: newTeam.trim() }), 'Rescue team created.').then((success) => { if (success) setNewTeam('') }) }
  return <section className="rescue-content"><header className="content-title resource-title"><div><h2>Rescue teams</h2><p>Manage operational teams, team members, and team vehicles.</p></div></header>
    {notice && <div className={notice.type === 'success' ? 'alert rescue-feedback--success' : 'alert'} role="alert">{notice.message}</div>}
    <form className="resource-add panel" onSubmit={createTeam}><h3>Add Rescue Team</h3><input value={newTeam} onChange={(e) => setNewTeam(e.target.value)} placeholder="Team name" maxLength={150} required /><button className="btn" disabled={busy}>Create Team</button></form>
    {!teams.length && <p className="empty">No rescue teams yet. Add your first team.</p>}
    <div className="team-grid">{teams.map((team) => <article className="team-card" key={team.id}><header><div><h2>{team.name}</h2><span className="status-chip">{team.status}</span></div><span>{team.members.length} members · {team.vehicles.length} vehicles</span></header>
      <details><summary>Edit Team</summary><form className="resource-form" onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); void run(() => updateRescueTeam(team.id, { ...team, name: String(f.get('name')), status: String(f.get('status')) as RescueTeamDto['status'], baseLatitude: team.baseLatitude, baseLongitude: team.baseLongitude }), 'Team updated.') }}><input name="name" defaultValue={team.name} required maxLength={150}/><select name="status" defaultValue={team.status}><option>Available</option><option>OnMission</option><option>OffDuty</option></select><button className="btn-ghost" disabled={busy}>Save</button></form></details>
      <section><h3>Team Members</h3>{team.members.map((member) => <details key={member.id} className="resource-item"><summary><strong>{member.fullName}</strong> · {member.skill} · {member.isAvailable ? 'Available' : 'Unavailable'}</summary><form className="resource-form" onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); void run(() => updateTeamMember(team.id, member.id, { fullName:String(f.get('fullName')), phone:String(f.get('phone')), skill:String(f.get('skill')) as SkillType, isAvailable:f.get('isAvailable') === 'on' }), 'Team member updated.') }}><input name="fullName" defaultValue={member.fullName} required/><MemberPhoneField defaultValue={member.phone}/><select name="skill" defaultValue={member.skill}>{skills.map((skill)=><option key={skill}>{skill}</option>)}</select><label><input name="isAvailable" type="checkbox" defaultChecked={member.isAvailable}/> Available</label><button className="btn-ghost" disabled={busy}>Save</button><button type="button" className="btn-ghost" disabled={busy} onClick={() => { if(confirm(`Remove ${member.fullName}?`)) void run(() => removeTeamMember(team.id, member.id), 'Team member removed.', 'destructive') }}>Remove</button></form></details>)}<details><summary>+ Add Team Member</summary><MemberForm busy={busy} onSubmit={(request) => run(() => addTeamMember(team.id, request), 'Team member added.')}/></details></section>
      <section><h3>Vehicles</h3>{team.vehicles.map((vehicle) => <details key={vehicle.id} className="resource-item"><summary><strong>{vehicle.plateNumber}</strong> · {vehicle.type} · capacity {vehicle.capacity} · {vehicle.status}</summary><form className="resource-form" onSubmit={(e) => { e.preventDefault(); const f=new FormData(e.currentTarget); void run(() => updateVehicle(team.id, vehicle.id, { plateNumber:String(f.get('plateNumber')), type:String(f.get('type')) as VehicleType, status:String(f.get('status')) as typeof vehicle.status, capacity:Number(f.get('capacity')) }), 'Vehicle updated.') }}><input name="plateNumber" defaultValue={vehicle.plateNumber} required/><select name="type" defaultValue={vehicle.type}>{vehicleTypes.map((type)=><option key={type}>{type}</option>)}</select><select name="status" defaultValue={vehicle.status}><option>Available</option><option>InUse</option><option>UnderMaintenance</option></select><input name="capacity" type="number" min="1" max="100" defaultValue={vehicle.capacity} required/><button className="btn-ghost" disabled={busy}>Save</button><button type="button" className="btn-ghost" disabled={busy} onClick={() => { if(confirm(`Remove ${vehicle.plateNumber}?`)) void run(() => removeVehicle(team.id, vehicle.id), 'Vehicle removed.', 'destructive') }}>Remove</button></form></details>)}<details><summary>+ Add Vehicle</summary><VehicleForm busy={busy} onSubmit={(request) => run(() => addVehicle(team.id, request), 'Vehicle added.')}/></details></section>
      <button type="button" className="btn-ghost" disabled={busy} onClick={() => { if(confirm(`Delete ${team.name}? This is blocked when operational history exists.`)) void run(() => deleteRescueTeam(team.id), 'Rescue team deleted.', 'destructive') }}>Delete Team</button></article>)}</div></section>
}

function MemberForm({ busy, onSubmit }: { busy:boolean; onSubmit:(request:CreateTeamMemberRequest)=>Promise<boolean> }) { return <form className="resource-form" onSubmit={(e)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void onSubmit({fullName:String(f.get('fullName')),phone:String(f.get('phone')),skill:String(f.get('skill')) as SkillType}).then((success) => { if (success) form.reset() })}}><input name="fullName" placeholder="Full name" required/><MemberPhoneField/><select name="skill">{skills.map((skill)=><option key={skill}>{skill}</option>)}</select><button className="btn-ghost" disabled={busy}>Add Member</button></form> }
function VehicleForm({ busy, onSubmit }: { busy:boolean; onSubmit:(request:CreateVehicleRequest)=>Promise<boolean> }) { return <form className="resource-form" onSubmit={(e)=>{e.preventDefault();const form=e.currentTarget;const f=new FormData(form);void onSubmit({plateNumber:String(f.get('plateNumber')),type:String(f.get('type')) as VehicleType,capacity:Number(f.get('capacity'))}).then((success) => { if (success) form.reset() })}}><input name="plateNumber" placeholder="Registration number" required/><select name="type">{vehicleTypes.map((type)=><option key={type}>{type}</option>)}</select><input name="capacity" type="number" min="1" max="100" defaultValue="1" required/><button className="btn-ghost" disabled={busy}>Add Vehicle</button></form> }
