// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RescueSriLanka.Api.Features.ComponentD.Data;

#nullable disable

namespace RescueSriLanka.Api.Migrations
{
    [DbContext(typeof(ComponentDDbContext))]
    [Migration("20260918131705_AddComponentD")]
    partial class AddComponentD
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Assignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HelpRequestId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IncidentId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("RequiredSkill")
                        .HasColumnType("integer");

                    b.Property<Guid>("RescueTeamId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RescueTeamId");

                    b.ToTable("Assignments");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Dispatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ApprovedByUserId")
                        .HasColumnType("text");

                    b.Property<Guid>("AssignmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DispatchedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EnRouteAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("OnSceneAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssignmentId")
                        .IsUnique();

                    b.ToTable("Dispatches");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.RescueTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double?>("BaseLatitude")
                        .HasColumnType("double precision");

                    b.Property<double?>("BaseLongitude")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("RescueTeams");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.TeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RescueTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Skill")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RescueTeamId");

                    b.ToTable("TeamMembers");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("PlateNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("RescueTeamId")
                        .HasColumnType("uuid");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("Type")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("RescueTeamId");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Assignment", b =>
                {
                    b.HasOne("RescueSriLanka.Api.Features.ComponentD.Models.RescueTeam", "RescueTeam")
                        .WithMany("Assignments")
                        .HasForeignKey("RescueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueTeam");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Dispatch", b =>
                {
                    b.HasOne("RescueSriLanka.Api.Features.ComponentD.Models.Assignment", "Assignment")
                        .WithOne("Dispatch")
                        .HasForeignKey("RescueSriLanka.Api.Features.ComponentD.Models.Dispatch", "AssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assignment");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.TeamMember", b =>
                {
                    b.HasOne("RescueSriLanka.Api.Features.ComponentD.Models.RescueTeam", "RescueTeam")
                        .WithMany("Members")
                        .HasForeignKey("RescueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueTeam");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Vehicle", b =>
                {
                    b.HasOne("RescueSriLanka.Api.Features.ComponentD.Models.RescueTeam", "RescueTeam")
                        .WithMany("Vehicles")
                        .HasForeignKey("RescueTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RescueTeam");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.Assignment", b =>
                {
                    b.Navigation("Dispatch");
                });

            modelBuilder.Entity("RescueSriLanka.Api.Features.ComponentD.Models.RescueTeam", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Members");

                    b.Navigation("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
