import 'dart:convert';

import 'help_request_api.dart';

// Matches HelpRequestType enum: Water=0, Food=1, Medical=2, Rescue=3, Shelter=4, Other=5
const List<String> helpRequestTypeLabels = [
  'Water',
  'Food',
  'Medical',
  'Rescue',
  'Shelter',
  'Other',
];

// Matches HelpRequestStatus enum
const List<String> helpRequestStatusLabels = [
  'Pending',
  'Assigned',
  'In Progress',
  'Resolved',
  'Cancelled',
];

// Matches VerificationStatus enum
const List<String> verificationStatusLabels = [
  'Pending Verification',
  'Verified',
  'Rejected (Fake)',
];

class HelpRequest {
  final String id;
  final int type;
  final String description;
  final double latitude;
  final double longitude;
  final int urgencyScore;
  final int status;
  final int verificationStatus;
  final String? verificationNotes;
  final String? imageUrl;
  final DateTime createdAt;

  HelpRequest({
    required this.id,
    required this.type,
    required this.description,
    required this.latitude,
    required this.longitude,
    required this.urgencyScore,
    required this.status,
    required this.verificationStatus,
    required this.verificationNotes,
    required this.imageUrl,
    required this.createdAt,
  });

  factory HelpRequest.fromJson(Map<String, dynamic> json) => HelpRequest(
    id: json['id'],
    type: json['type'],
    description: json['description'],
    latitude: (json['latitude'] as num).toDouble(),
    longitude: (json['longitude'] as num).toDouble(),
    urgencyScore: json['urgencyScore'],
    status: json['status'],
    verificationStatus: json['verificationStatus'],
    verificationNotes: json['verificationNotes'],
    imageUrl: json['imageUrl'],
    createdAt: DateTime.parse(json['createdAt']),
  );
}

class StatusHistoryEntry {
  final int oldStatus;
  final int newStatus;
  final String? notes;
  final DateTime changedAt;

  StatusHistoryEntry({
    required this.oldStatus,
    required this.newStatus,
    required this.notes,
    required this.changedAt,
  });

  factory StatusHistoryEntry.fromJson(Map<String, dynamic> json) =>
      StatusHistoryEntry(
        oldStatus: json['oldStatus'],
        newStatus: json['newStatus'],
        notes: json['notes'],
        changedAt: DateTime.parse(json['changedAt']),
      );
}

/// Supplemental guidance generated by the server-side AI service.
/// It never decides whether a request receives an emergency response.
class AiRequestAnalysis {
  final String reasoning;
  final String suggestedAction;

  AiRequestAnalysis({required this.reasoning, required this.suggestedAction});

  factory AiRequestAnalysis.fromJson(Map<String, dynamic> json) =>
      AiRequestAnalysis(
        reasoning: json['reasoning'] as String? ?? '',
        suggestedAction: json['suggestedAction'] as String? ?? '',
      );
}

class AiPriority {
  final String priority;
  final bool aiAnalysisAvailable;

  AiPriority({required this.priority, required this.aiAnalysisAvailable});

  factory AiPriority.fromJson(Map<String, dynamic> json) => AiPriority(
    priority: json['priority'] as String? ?? 'Analysis pending',
    aiAnalysisAvailable: json['aiAnalysisAvailable'] as bool? ?? false,
  );
}

class HelpRequestLoadResult {
  final List<HelpRequest> requests;
  final String? error;

  const HelpRequestLoadResult({required this.requests, this.error});
}

class HelpRequestService {
  static Future<HelpRequest?> submit({
    required int type,
    required String description,
    required double latitude,
    required double longitude,
    String? imageUrl,
  }) async {
    final res = await HelpRequestApi.post('/api/HelpRequests', {
      'type': type,
      'description': description,
      'latitude': latitude,
      'longitude': longitude,
      'relatedIncidentId': null,
      'imageUrl': imageUrl,
    });

    if (res.statusCode == 200 || res.statusCode == 201) {
      return HelpRequest.fromJson(jsonDecode(res.body));
    }
    return null;
  }

  static Future<List<HelpRequest>> getMine() async {
    return (await getMineWithStatus()).requests;
  }

  static Future<HelpRequestLoadResult> getAllWithStatus() =>
      _loadRequests('/api/HelpRequests');

  /// Keeps a failed request fetch distinct from a genuine empty request list.
  static Future<HelpRequestLoadResult> getMineWithStatus() async {
    return _loadRequests('/api/HelpRequests/mine');
  }

  static Future<HelpRequestLoadResult> _loadRequests(String path) async {
    try {
      final res = await HelpRequestApi.get(path);
      if (res.statusCode == 401) {
        return const HelpRequestLoadResult(
          requests: [],
          error: 'Your session has expired. Please sign in again.',
        );
      }
      if (res.statusCode != 200) {
        return const HelpRequestLoadResult(
          requests: [],
          error: 'Could not load your requests. Pull down or tap refresh to try again.',
        );
      }
      final List<dynamic> data = jsonDecode(res.body);
      return HelpRequestLoadResult(
        requests: data.map((json) => HelpRequest.fromJson(json)).toList(),
      );
    } catch (_) {
      return const HelpRequestLoadResult(
        requests: [],
        error: 'Could not reach the request service. Check your connection and API server.',
      );
    }
  }

  static Future<List<StatusHistoryEntry>> getHistory(String id) async {
    final res = await HelpRequestApi.get('/api/HelpRequests/$id/history');
    if (res.statusCode != 200) return [];

    final List<dynamic> data = jsonDecode(res.body);
    return data.map((json) => StatusHistoryEntry.fromJson(json)).toList();
  }

  static Future<AiRequestAnalysis?> getAiAnalysis(String id) async {
    final res = await HelpRequestApi.post(
      '/api/HelpRequests/$id/ai-analysis',
      {},
    );
    if (res.statusCode != 200) return null;
    return AiRequestAnalysis.fromJson(
      jsonDecode(res.body) as Map<String, dynamic>,
    );
  }

  static Future<AiPriority?> getAiPriority(String id) async {
    final res = await HelpRequestApi.get('/api/HelpRequests/$id/ai-priority');
    if (res.statusCode != 200) return null;
    return AiPriority.fromJson(jsonDecode(res.body) as Map<String, dynamic>);
  }

  static Future<AiRequestAnalysis?> analyzeDraft({
    required int type,
    required String description,
  }) async {
    final res = await HelpRequestApi.post(
      '/api/HelpRequests/ai-draft-analysis',
      {'type': type, 'description': description},
    );
    if (res.statusCode != 200) return null;
    return AiRequestAnalysis.fromJson(
      jsonDecode(res.body) as Map<String, dynamic>,
    );
  }

  static Future<bool> update({
    required HelpRequest request,
    required int type,
    required String description,
  }) async {
    final res = await HelpRequestApi.put('/api/HelpRequests/${request.id}', {
      'type': type,
      'description': description,
      'latitude': request.latitude,
      'longitude': request.longitude,
      'relatedIncidentId': null,
      'imageUrl': request.imageUrl,
    });
    return res.statusCode == 200;
  }

  static Future<bool> cancel(String id) async {
    final res = await HelpRequestApi.delete('/api/HelpRequests/$id');
    return res.statusCode == 204;
  }
}
